name: Deploy to VPS

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19.1"

            - name: Install dependencies
              run: go get .

            - name: Build
              run: GOARCH=arm64 go build -v -o main main.go

            - name: Copy binary via scp
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSHKEY }}
                  source: "main"
                  target: "~/github/yt-synchronizer-backend"

            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSHKEY }}
                  script: |
                      sudo service yt-sychronizer-backend restart
