name: Deploy to VPS

on:
    push:
        branches: -main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19.1"

            - name: Install dependencies
              run: go get .

            - name: Build
              run: go build -v -o main ./...

            - name: Copy binary via scp
              uses: appleboy/scp-action@master
              env:
                  HOST: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  KEY: ${{ secrets.SSHKEY }}
              with:
                  source: "main"
                  target: "~/github/yt-synchronizer-backend"

            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSHKEY }}
                  script: |
                      cd github/yt-synchronizer-backend
                      ls
